### ISSUE TITLE
nginx worker process doesn't exit when nginx reload configuration.

### ISSUE THREAD

**Issue by bluezheng** [GUI/nginx-upstream-dynamic-servers#1]
Compiled nginx upstream dynamic servers module with nginx 1.7.7.

When execute command "sudo nginx -s reload", a new worker process started, but existed worker process always show status as "is shutting down" but never exit.

**Comment by k2s** [comment]
this bug makes this otherwise very useful module unusable. is this project still maintained ?

**Comment by GUI** [comment]
Very sorry for the absurdly long delay in following up. I'm unfortunately not using this module at the moment, so I'm afraid I don't have time to look into this, but any pull requests are welcome.

**Comment by GUI** [comment]
Thanks to @wandenberg's recent contributions, this should hopefully be resolved now. Give a shout if not.
