### ISSUE TITLE
Add support for nginx 1.6.2 stable

### ISSUE THREAD

**Issue by crosbymichael** [GUI/nginx-upstream-dynamic-servers#2]
I'm looking into the issue but it seems simple for someone that knows the nginx api.

The error message is from `ngx_http_upstream_server_t` not having a `name` field in 1.6.2

```bash
/root/nginx/nginx-upstream-dyanmic-servers/ngx_http_upstream_dynamic_servers.c:212:5: error: ‘ngx_http_upstream_server_t’ has no member named ‘name’
   us->name = u.url;
     ^
`

**Comment by GUI** [comment]
Very sorry for the super-long delay! I was only targeting nginx 1.7 when I first built this, but any pull requests are welcome for older versions.
