### ISSUE TITLE
Support for NGINX 1.7.10

### ISSUE THREAD

**Issue by johnpeak** [GUI/nginx-upstream-dynamic-servers#4]
Agreed this module works great.  Any chance you'd have time to upgrade to the 1.7.10 version?  Thank you.

**Comment by GUI** [comment]
Apologies for the super-long delay! I'm afraid I'm not actively using this module at the moment so I probably won't have the time to look into this, but any pull requests for compatibility with other nginx versions are welcome.

**Comment by johnpeak** [comment]
Hi Nick

Thanks for the response and no worries.  I had to migrate over to using jdomain since this version was giving me segfaults under high load.  My setup can reach up to 800TPS and I noticed it crashing after a day.  Things seem pretty stable now.  I appreciate your work on this.  It certainly helped me evolve my understanding of how to configure this.

thx
john

From: Nick Muerdter
Reply-To: GUI/nginx-upstream-dynamic-servers
Date: Monday, November 23, 2015 at 4:16 PM
To: GUI/nginx-upstream-dynamic-servers
Cc: John Peak
Subject: Re: [nginx-upstream-dynamic-servers] Support for NGINX 1.7.10 (#4)


Apologies for the super-long delay! I'm afraid I'm not actively using this module at the moment so I probably won't have the time to look into this, but any pull requests for compatibility with other nginx versions are welcome.

—
Reply to this email directly or view it on GitHub<https://github.com/GUI/nginx-upstream-dynamic-servers/issues/4#issuecomment-159066504>.

CONFIDENTIALITY  NOTICE: This message is intended for the use of the individual or entity to which it is addressed and may contain information that is confidential, privileged and exempt from disclosure under applicable law. If the reader of this message is not the intended recipient, you are hereby notified that any printing, copying, dissemination, distribution, disclosure or forwarding of this communication is strictly prohibited. If you have received this communication in error, please contact the sender immediately and delete it from your system. Thank You.

**Comment by wandenberg** [comment]
It is working with 1.7.10, at least with this [branch](https://github.com/wandenberg/nginx-upstream-dynamic-servers)

**Comment by GUI** [comment]
Thanks to @wandenberg's efforts, the sporadic segfaults fixes should now be on master. Thanks @wandenberg! Let us know if you're still seeing any issues, though.
