### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by nikolay** [GUI/nginx-upstream-dynamic-servers#5]
Even the repo name has a typo. On a side note, is the project still active?

**Comment by GUI** [comment]
Whoops, well that's embarrassing!

![](https://media.giphy.com/media/4pMX5rJ4PYAEM/giphy.gif)

Thanks for spotting that! I've fixed it now.

I'm not actively using this module at the moment, so unfortunately I haven't had time to make any updates (I think there are some compatibility issues with nginx 1.9). But any pull requests are welcome.

**Comment by nikolay** [comment]
@GUI Thanks for the quick response! Nobody is immune from ~~typoes~~ typos!
