### ISSUE TITLE
Update for newer nginx versions?

### ISSUE THREAD

**Issue by neilstuartcraig** [GUI/nginx-upstream-dynamic-servers#7]
Hi @GUI 

This looks like the perfect module to fit my needs but it won't compile against nginx 1.9.11 current latest). I just wondered if you have any plans to support newer builds?

Cheers
Neil

**Comment by GUI** [comment]
I'm afraid I'm not actively using this module at the moment, so I unfortunately won't have time to look into updating it. However, I'd be more than happy to accept any pull requests or new maintainers.

And this might not be too relevant for your usage, but simply for reference, on my [current project](https://github.com/NREL/api-umbrella), I'm achieving dynamic DNS handling in OpenResty with the lua integration of [ngx_http_dyups_module](https://github.com/yzprofile/ngx_http_dyups_module) (and probably eventually switching over to the new [balancer_by_lua](https://github.com/openresty/lua-nginx-module#balancer_by_lua_block)). But that approach is admittedly more work (you have to do the DNS resolution yourself with [lua-resty-dns](https://github.com/openresty/lua-resty-dns)), and is mainly beneficial if you want dynamically created backends via OpenResty and a Lua codebase. But I'll also add some links to those approaches under the Alternatives section.
